### ISSUE TITLE
dirhtml builder errors with files called `index`

### ISSUE THREAD

**Issue by choldgraf** [wpilibsuite/sphinxext-rediraffe#36]
I'm using this plugin for a Sphinx site that has some pages called `index.rst` (e.g. `docs/mydir/index.rst`). When using the `dirhtml` builder, Sphinx does *not* create an extra folder for `index` (e.g. `docs/mydir/index/index.html`) and instead just leaves the index file as-is (`docs/mydir/index.html`), but this extension *searches* for this file when checking whether this file exists. Has anybody else run into this issue or know a workaround?

**Comment by TheTripleV** [comment]
Rediraffe currently does not properly account for index.rst files in folders. The linked pr should resolve it.

When redirecting to a file, rediraffe makes sure that the file actually exists.

**Comment by choldgraf** [comment]
Wow that was a fast turnaround!! Thanks so much 🙂
